"""VISTA is a PRE-TRAINING structural verifier: trainable parameter VALUES
must never participate in verification (final engineering pass, Task 3).
This is the regression the spec asks for: two artifacts exported from the
*same* architecture (`examples/dft/models/structural_gnns.CertifiedRingGNN`)
with different `torch.manual_seed` calls -- i.e. different initial
`base_operator` floating-point values -- must:

  1. have different `artifact_sha256` (the whole-file hash genuinely
     depends on the artifact's exact bytes, floats included);
  2. produce byte-identical raw extraction inventories and structural IR
     (`extractors.torch_export_worker.extract`'s `inventory` never records
     a trainable parameter's actual values or a content hash of them --
     only shape/dtype/state_kind/graph_inputs/aliases, none of which are
     affected by re-initializing the same architecture);
  3. derive the same formal binding candidates and certify the same
     result under the same package/entrypoint.

Fixtures (`tests/fixtures/certified_ring_seed_a.pt2`/`_seed_b.pt2`) are
pre-generated by `tests/fixtures/export_pass_fixtures.py` (needs torch;
committed as binary fixtures like `certified_ring.pt2`, not regenerated at
test time).
"""
import json
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory

from dftcert.structural.core import structural_ir_from_inventory
from dftcert.structural.dft_capability_plugin import DFT_CAPABILITY_PLUGIN
from dftcert.verification import VerificationPackageBuilder, certify_session, start_session
from extractors.torch_export_worker import extract

from tests.test_lean_introspection import _HAS_LEAN, _SKIP_REASON

PROJECT = Path(__file__).resolve().parent.parent / "examples" / "dft" / "lean"
FIXTURES = Path(__file__).resolve().parent / "fixtures"
SEED_A = FIXTURES / "certified_ring_seed_a.pt2"
SEED_B = FIXTURES / "certified_ring_seed_b.pt2"
ENTRYPOINT = "Testv2.Requirements.ValidSelfAdjointConstruction"
CONSTRAINTS = {
    "adjacency_convention": "target_source",
    "output_contracts": [
        {"index": 0, "role": "xc_energy"},
        {"index": 1, "role": "learned_self_energy"},
        {"index": 2, "role": "message_state"},
    ],
    "long_range_pairs": [[0, 3]],
}

_FIXTURES_MISSING = "" if (SEED_A.is_file() and SEED_B.is_file()) else (
    f"run `python {FIXTURES / 'export_pass_fixtures.py'}` (needs torch) to generate "
    f"{SEED_A.name}/{SEED_B.name} first"
)


@unittest.skipIf(_FIXTURES_MISSING, _FIXTURES_MISSING)
class DifferentInitializationTests(unittest.TestCase):
    def test_artifact_hash_differs_but_inventory_does_not(self):
        result_a = extract(SEED_A)
        result_b = extract(SEED_B)
        self.assertNotEqual(result_a["artifact_sha256"], result_b["artifact_sha256"])
        # No trainable parameter's actual float values (or a content hash
        # of them) are ever recorded -- only architecture-level metadata --
        # so re-initializing the same architecture produces a byte-
        # identical raw inventory.
        self.assertEqual(result_a["inventory"], result_b["inventory"])

    def test_structural_ir_and_formal_candidates_are_identical(self):
        result_a = extract(SEED_A)
        result_b = extract(SEED_B)
        ir_a = structural_ir_from_inventory(
            inventory=result_a["inventory"], artifact_sha256=result_a["artifact_sha256"],
            extractor_version=result_a["extractor_version"], input_constraints=CONSTRAINTS,
            plugin=DFT_CAPABILITY_PLUGIN,
        )
        ir_b = structural_ir_from_inventory(
            inventory=result_b["inventory"], artifact_sha256=result_b["artifact_sha256"],
            extractor_version=result_b["extractor_version"], input_constraints=CONSTRAINTS,
            plugin=DFT_CAPABILITY_PLUGIN,
        )
        # `source.artifact_sha256` legitimately differs (it is bound to the
        # exact bytes, on purpose); every relevant structural classification
        # does not.
        self.assertNotEqual(ir_a["source"]["artifact_sha256"], ir_b["source"]["artifact_sha256"])
        self.assertEqual(ir_a["source"]["parameter_structure_sha256"], ir_b["source"]["parameter_structure_sha256"])
        self.assertEqual(ir_a["operator"], ir_b["operator"])
        self.assertEqual(ir_a["topology"], ir_b["topology"])
        self.assertEqual(ir_a["xc"], ir_b["xc"])
        self.assertEqual(ir_a["capabilities"], ir_b["capabilities"])

        candidates_a = DFT_CAPABILITY_PLUGIN.formal_binding_candidates(ir_a)
        candidates_b = DFT_CAPABILITY_PLUGIN.formal_binding_candidates(ir_b)
        self.assertEqual(
            [(c.key, c.lean_expr, c.provenance) for c in candidates_a],
            [(c.key, c.lean_expr, c.provenance) for c in candidates_b],
        )

    @unittest.skipUnless(_HAS_LEAN, _SKIP_REASON)
    def test_same_verification_result_regardless_of_initialization(self):
        for artifact in (SEED_A, SEED_B):
            with self.subTest(artifact=artifact.name), TemporaryDirectory() as tmp:
                result = extract(artifact)
                package_path = Path(tmp) / "package.json"
                VerificationPackageBuilder(
                    lean_project=PROJECT, entrypoints=[ENTRYPOINT], adapter=DFT_CAPABILITY_PLUGIN,
                    interface_contract=CONSTRAINTS,
                ).write(package_path)
                extraction_path = Path(tmp) / "extraction.json"
                extraction_path.write_text(json.dumps(result), encoding="utf-8")
                session_path = Path(tmp) / "session.json"
                session = start_session(
                    extraction_result=str(extraction_path), package=str(package_path),
                    session=str(session_path), project=str(PROJECT), trusted_local=True, timeout_s=180,
                )
                self.assertEqual(session.status, "ready_for_certificate")
                manifest = certify_session(
                    session=str(session_path), package=str(package_path), project=str(PROJECT),
                    output_dir=str(Path(tmp) / "certificate"),
                    extraction_result=str(extraction_path), trusted_local=True, timeout_s=180,
                )
                self.assertEqual(manifest["status"], "certified")


if __name__ == "__main__":
    unittest.main()
