name = "vista-dft-example"
version = "0.1.0"
keywords = ["math", "dft", "verification"]
defaultTargets = ["Testv2"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.header = false
weak.linter.style.emptyLine = false
weak.linter.unusedSectionVars = false
weak.linter.unusedFintypeInType = false
weak.linter.unusedDecidableInType = false
weak.linter.unusedSimpArgs = false
weak.linter.flexible = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0"

[[lean_lib]]
name = "Testv2"
